export const ActionTypes = {
  SET_USERS: "SET_USERS",
  SET_REQUESTS: "SET_REQUESTS",
  SELECTED_USER: "SELECTED_USER",
  SELECTED_REQUEST: "SELECTED_REQUEST",
  REMOVE_SELECTED_USER: "REMOVE_SELECTED_USER",
  REMOVE_SELECTED_REQUEST: "REMOVE_SELECTED_REQUEST",
};
